version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/Taskapp
    depends_on:
      db:
        condition: service_healthy
    networks:
      - Task-net

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - Task-net

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Taskapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SQL", "postgres", "-U", "postgres", "-c", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - Task-net

volumes:
  pgdata:

networks:
  Task-net:
    driver: bridge
